#### Preamble ####
# Purpose: Figure 2 replication
# Author: Yunzhao Li, Yang Cheng, Wentao Sun
# Date: 14 February 2024
# Contact: yunzhao.li@mail.utoronto.ca
# License: MIT
# Pre-requisites: download_data.R, data_cleaning.R

## Data Sources:
# Data about frequencies and percentages generated by the descriptives and 
# propTest2 functions in data_cleaning.R


#### Workspace setup ####
# Load libraries
library(ggplot2)
library(scales)
library(knitr)
library(MBESS)
library(psych)
library(dplyr) 
library(Hmisc)
library(effsize)
library(jmv)
library(Rcpp)
library(reshape2)
library(readr)
library(janitor)
library(tidyverse)
library(kableExtra)

# Read in the raw data.
fig1_data <- read_csv("inputs/data/fig_1.csv")

# Data in percentage for Adams and White we gained from the table we created
# Ensure that the percentages are divided by 100 to be in the correct format
data <- data.frame(
  Category = c('Regret', 'Luck'),
  Adams_Routine = c(19.0 / 100, 33.3 / 100), # Convert to proportions
  White_Exception = c(81.0 / 100, 66.7 / 100) # Convert to proportions
)

# Melt the data for use with ggplot2
data_melted <- melt(data, id.vars='Category')

# Create the bar plot with specified colors and corrected percentage values
ggplot(data_melted, aes(x = Category, y = value, fill = variable)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c('Adams_Routine' = '#1f77b4', 'White_Exception' = '#d62728')) +
  theme_minimal() +
  labs(x = '', y = 'Percentage (%)', fill = '') +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = 'bottom',
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    plot.title = element_text(hjust = 0.5)
  ) +
  scale_y_continuous(labels = percent_format()) + # This will ensure y-axis is formatted as percentage
  ggtitle('Proportions for regret and luck')