#### Preamble ####
# Purpose: Table 1 replication
# Author: Yunzhao Li, Yang Cheng, Wentao Sun
# Date: 14 February 2024
# Contact: yunzhao.li@mail.utoronto.ca
# License: MIT
# Pre-requisites: download_data.R, data_cleaning.R

## Data Sources:
# Data about frequencies and percentages generated by the descriptives and 
# propTest2 functions in data_cleaning.R


#### Workspace setup ####
# Load libraries
library(ggplot2)
library(scales)
library(knitr)
library(MBESS)
library(psych)
library(dplyr) 
library(Hmisc)
library(effsize)
library(jmv)
library(Rcpp)
library(reshape2)
library(readr)
library(janitor)
library(tidyverse)
library(kableExtra)


# Read in the raw data.
data <- read.csv(here::here("data/raw_data/osf-past-normality-regret-replication-exp1-data.csv"), header = TRUE, stringsAsFactors = FALSE, fileEncoding = "UTF-8-BOM")

# JAMOVI requires factors, while R imports as numeric. So, need to convert from numeric to factor.
data$Sc1_regret<- factor(data$Sc1_regret)
data$sc1_socnorms1<- factor(data$sc1_socnorms1)
data$sc1_socnorms2<- factor(data$sc1_socnorms2)
data$sc1_combinednorms<- factor(data$sc1_combinednorms)

# Let's label the values better, so it's easier to understand the output.
data$Sc1_regret <- ordered(data$Sc1_regret, levels = c(1,2), labels = c("Exception Jones", "Routine Smith"))
data$sc1_socnorms1 <- ordered(data$sc1_socnorms1, levels = c(1,2), labels = c("Exception Jones", "Routine Smith"))
data$sc1_socnorms2 <- ordered(data$sc1_socnorms2, levels = c(1,2), labels = c("Exception Jones", "Routine Smith"))
data$sc1_combinednorms <- ordered(data$sc1_combinednorms, levels = c(1,2), labels = c("Exception Jones", "Routine Smith"))

# R's way of doing binomial
# we need to count, while excluding NAs
x1 <- sum((data$Sc1_regret[!is.na(data$Sc1_regret)])=="Exception Jones")
n1 <- length(data$Sc1_regret[!is.na(data$Sc1_regret)])
prop.test(x1, n1, p=0.5, correct = FALSE)
result <- prop.test(x1, n1, p = 0.5, correct = FALSE)
p1 <- result$estimate["p"]

x2 <- sum((data$sc1_socnorms1[!is.na(data$sc1_socnorms1)])=="Exception Jones")
n2 <- length(data$sc1_socnorms1[!is.na(data$sc1_socnorms1)])
prop.test(x2, n2, p=0.5, correct = FALSE)
result <- prop.test(x2, n2, p = 0.5, correct = FALSE)
p2 <- result$estimate["p"]

x3 <- sum((data$sc1_socnorms2[!is.na(data$sc1_socnorms2)])=="Exception Jones")
n3 <- length(data$sc1_socnorms2[!is.na(data$sc1_socnorms2)])
prop.test(x3, n3, p=0.5, correct = FALSE)
result <- prop.test(x3, n3, p = 0.5, correct = FALSE)
p3 <- result$estimate["p"]

x4 <- sum((data$sc1_combinednorms[!is.na(data$sc1_combinednorms)])=="Exception Jones")
n4 <- length(data$sc1_combinednorms[!is.na(data$sc1_combinednorms)])
prop.test(x4, n4, p=0.5, correct = FALSE)
result <- prop.test(x4, n4, p = 0.5, correct = FALSE)
p4 <- result$estimate["p"]

# create a data frame to save the data
table_data <- data.frame(
  ` ` = c("Routine Smith", "Exception Jones"),
  Regret_Counts = c(n1 - x1, x1),
  Regret_Percent = c(round(100*(1 - p1), digits = 1), round(100*p1, digits = 1)),
  Social_Norm_Injunctive_Counts = c(n2 - x2, x2),
  Social_Norm_Injunctive_Percent = c(round(100*(1 - p2), digits = 1), round(100*p2, digits = 1)),
  Social_Norm_Descriptive_Counts = c(n3 - x3, x3),
  Social_Norm_Descriptive_Percent = c(round(100*(1 - p3), digits = 1), round(100*p3, digits = 1)),
  Negative_Affect_Counts = c(n4 - x4, x4),
  Negative_Affect_Percent = c(round(100*(1 - p4), digits = 1), round(100*p4, digits = 1))
)

# create the table with kable()
kable(table_data, format = "latex", col.names = c(" ", "Regret", "%", "Soc_norm1", "%", "Soc_norm2", "%", "Negetive affect", "%"), align = 'c')