#### Preamble ####
# Purpose: Table 2 replication
# Author: Yunzhao Li, Yang Cheng, Wentao Sun
# Date: 14 February 2024
# Contact: yunzhao.li@mail.utoronto.ca
# License: MIT
# Pre-requisites: download_data.R, data_cleaning.R

## Data Sources:
# Data about frequencies and percentages generated by the descriptives and 
# propTest2 functions in data_cleaning.R


#### Workspace setup ####
# Load libraries
library(ggplot2)
library(scales)
library(knitr)
library(MBESS)
library(psych)
library(dplyr) 
library(Hmisc)
library(effsize)
library(jmv)
library(Rcpp)
library(reshape2)
library(readr)
library(janitor)
library(tidyverse)
library(kableExtra)

# Create the data frame based on the the value we gained from the binomial test
data <- data.frame(
  Level = c("Routine Adams", "Exception White", "Routine Adams", "Exception White"),
  Count = c(65, 277, 114, 228),
  stringsAsFactors = FALSE
)

# Split the data frame into two based on the categories: Regret and Luck
regret_data <- data[1:2, ]
luck_data <- data[3:4, ]

# Add the percentages as a new column
regret_data$Percentage <- c(19.0, 81.0)
luck_data$Percentage <- c(33.3, 66.7)

# Combine the two data frames into a single data frame for display
final_data <- data.frame(
  ` ` = c("Regret", "", "Luck", ""),
  Level = c(regret_data$Level, luck_data$Level),
  Count = c(regret_data$Count, luck_data$Count),
  Percentage = c(regret_data$Percentage, luck_data$Percentage)
)

# Create a table
kable(final_data, col.names = c("", "Choice", "Count", "%"), align = c('l', 'l', 'r', 'r'))